### ISSUE TITLE
 CLR/System.MissingMethodException

### ISSUE THREAD

**Issue by jfaquinojr** [VeritasSoftware/AspNetCore.Security.Jwt#3]
I was giving this a try today, I dropped it on my project but:

Exception has occurred: CLR/System.MissingMethodException
An exception of type 'System.MissingMethodException' occurred in Swashbuckle.AspNetCore.SwaggerUI.dll but was not handled in user code: 'Method not found: 'Void Microsoft.AspNetCore.Builder.SwaggerUIOptionsExtensions.DocExpansion(Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIOptions, Microsoft.AspNetCore.Builder.DocExpansion)'.'
   at AspNetCore.Security.Jwt.SwaggerExtensions.<>c.<UseSwaggerDocumentation>b__9_0(SwaggerUIOptions c)
   at Microsoft.AspNetCore.Builder.SwaggerUIBuilderExtensions.UseSwaggerUI(IApplicationBuilder app, Action`1 setupAction)
   at AspNetCore.Security.Jwt.SwaggerExtensions.UseSwaggerDocumentation(IApplicationBuilder app)
   at AspNetCore.Security.Jwt.SecurityExtensions.UseSecurity(IApplicationBuilder app, Boolean addSwaggerSecurity)
   at Kooperatiba.Api.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/jokab/dev/kooperatiba/Server/Kooperatiba.Api/Startup.cs:line 98

my startup.cs:

 ```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(o => o.AddPolicy("MyPolicy", builder =>
            {
                builder.AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader();
            }));
            services.AddDbContext<KooperaContext>(options => {
                options.UseSqlite("DataSource=kooperatibay.db");
            });
            services.AddIdentity<KooperaUser, KooperaRole>(options => {
                options.Password.RequireDigit = false;
                options.Password.RequiredLength = 3;
                options.Password.RequireLowercase = false;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequiredUniqueChars = 0; 
                options.User.RequireUniqueEmail = true;
            })
            .AddDefaultTokenProviders()
            .AddEntityFrameworkStores<KooperaContext>();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Kooperatiba API", Version = "v1" });
            });
            services.AddSecurity<Authenticator>(this.Configuration, true);
            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                .AddJsonOptions(
                    options => options.SerializerSettings.ReferenceLoopHandling =  ReferenceLoopHandling.Ignore
                )
                .AddSecurity();
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHttpsRedirection();
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            // Enable middleware to serve generated Swagger as a JSON endpoint.
            //app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), 
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Kooperatiba API V1");
            });

            app.UseSecurity(true); //<-- error!!!

            app.UseMvc();
        }
```

appsettings.json:

```
{
    "SecuritySettings": {
        "SystemSettings": {
            "FacebookAuthSettings": {
                "OAuthUrl": "https://graph.facebook.com/oauth/access_token?client_id={0}&client_secret={1}&grant_type=client_credentials",
                "UserTokenValidationUrl": "https://graph.facebook.com/debug_token?input_token={0}&access_token={1}"
            },
            "GoogleAuthSettings": {
                "TokenUrl": "https://accounts.google.com/o/oauth2/token"
            },
            "TwitterAuthSettings": {
                "TokenUrl": "https://api.twitter.com/oauth2/token"
            }
        },
        "Secret": "the quick brown fox jumps over the lazy dog.",
        "Issuer": "Kooperatiba API",
        "Audience": "Kooperatiba Web",
        "IdType": "Name",
        "TokenExpiryInHours": 2
    },
    "AzureAdB2C": {
        "Instance": "https://login.microsoftonline.com/tfp/",
        "ClientId": "11111111-1111-1111-11111111111111111",
        "Domain": "qualified.domain.name",
        "SignUpSignInPolicyId": ""
    },
    "Logging": {
        "LogLevel": {
            "Default": "Warning"
        }
    },
    "AllowedHosts": "*"
}


```

Great project btw, thanks for sharing to the community!

**Comment by jfaquinojr** [comment]
Here is my project dependencies

```
<ItemGroup>
    <PackageReference Include="AspNetCore.Security.Jwt" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.WebApiCompatShim" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>
```
and my environment:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]
  2.2.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]


```

**Comment by jfaquinojr** [comment]
It turned out there was a mismatch on our versions of Swagger. 

I downgraded to your version from 4.0.1 to 3.0.0.

It's now working.

Closing this issue.

Thanks!

**Comment by jasenf** [comment]
I don't think this issue should be closed.  It prevents us from using the latest version of Swagger.
