### ISSUE TITLE
Getting error in .NET core 3.0 - Value cannot be null. (Parameter 'user')

### ISSUE THREAD

**Issue by mehul-brahmvar** [VeritasSoftware/AspNetCore.Security.Jwt#7]
First of all thanks for wonderful package for security. 

I am using AspNetCore.Security.Jwt with ASP.NET core 3.0 project and getting below error. Below are changes done in Startup.cs

`public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSecurity(false);
            app.UseMvc();
        }`

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddSecurity<Authenticator, UserModel>(this.Configuration, builder =>
                builder.AddClaim(IdType.Name, userModel => userModel.Id)
            , false);
            services.AddMvc(ep=>ep.EnableEndpointRouting = false).AddSecurity<UserModel>();
        }`
Below are settings done in appSettings.json
`{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "SecuritySettings": {
    "SystemSettings": {
      "FacebookAuthSettings": {
        "OAuthUrl": "https://graph.facebook.com/oauth/access_token?client_id={0}&client_secret={1}&grant_type=client_credentials",
        "UserTokenValidationUrl": "https://graph.facebook.com/debug_token?input_token={0}&access_token={1}"
      },
      "GoogleAuthSettings": {
        "TokenUrl": "https://accounts.google.com/o/oauth2/token"
      },
      "TwitterAuthSettings": {
        "TokenUrl": "https://api.twitter.com/oauth2/token"
      }
    },
    "Secret": "a secret that needs to be at least 16 characters long",
    "Issuer": "your app",
    "Audience": "the client of your app",
    "IdType": "Name",
    "TokenExpiryInHours": 1.2
  }
}
`

**ERROR:**

AspNetCore.Security.Jwt.SecurityException: Value cannot be null. (Parameter 'user')
   at AspNetCore.Security.Jwt.TokenController`1.Create(TUserModel user)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by mehul-brahmvar** [comment]
There was an issue in passing json payload. Fixed it in my code. Closing this issue.
